services:
  - type: web
    name: monopoly-al-sharq
    env: node
    buildCommand: npm run build
    startCommand: cd server && node index.js
    envVars:
      - key: NODE_ENV
        value: production
